[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
data-collector = { path = "../collector" }

[[bin]]
name = "cli"
path = "src/main.rs" 